# Generated by Django 5.0.14 on 2025-11-13 14:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offering',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(unique=True)),
                ('name', models.CharField(max_length=120)),
                ('duration_minutes', models.PositiveIntegerField(default=60)),
                ('price_eur', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
            options={
                'verbose_name': 'Oferta',
                'verbose_name_plural': 'Ofertas',
            },
        ),
        migrations.AlterField(
            model_name='reservation',
            name='service',
            field=models.CharField(blank=True, choices=[('masaje', 'Masaje y Osteopatía'), ('biomagnetico', 'Par Biomagnético'), ('emocionales', 'Técnicas Emocionales'), ('nutricional', 'Asesoramiento Nutricional y Estilo de Vida')], max_length=20, verbose_name='Servicio'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='offering',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reservations', to='reservas.offering'),
        ),
    ]
