# Generated by Django 5.0.14 on 2025-11-17 15:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_offering_alter_reservation_service_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='phone',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(code='invalid_phone', message='El teléfono debe contener entre 7 y 15 caracteres (dígitos, espacios, guiones o paréntesis)', regex='^[\\d\\s\\-\\(\\)\\+]{7,15}$')], verbose_name='Teléfono'),
        ),
    ]
